cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.CartDetailView.as_view(), name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

food_delivery_service/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from shop.views import *
from django.views.decorators.csrf import csrf_exempt

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('orders.urls', namespace='orders')),
    path('', include('shop.urls')),
    path('shop', include('shop.urls', namespace='shop')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('webhook/', csrf_exempt(my_webhook_handler))
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        # ...
        path('__debug__/', include('debug_toolbar.urls')),
    ] + urlpatterns

    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = pageNotFound

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.YooMoneyCheckoutWidget.as_view(), name='order_create'),
]

shop/urls.py
from django.urls import path
from .views import *
from django.views.decorators.csrf import csrf_exempt

app_name = 'shop'

urlpatterns = [
    path('', ProductsHome.as_view(), name='shop'),
    path('<slug>', ProductsHome.as_view(), name='shop'),
    path('city/<slug:city_slug>', city_slug, name='city_slug'),
    path('contacts/', contacts, name='contacts'),
    path('jobs/', jobs, name='jobs'),
    path('category/<slug:cat_slug>/', ProductsCategory.as_view(), name='category'),
    path('product/<slug:post_slug>/', ShowProduct.as_view(), name='product'),
    path('webhook/', csrf_exempt(my_webhook_handler))
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int, widget=forms.HiddenInput(), initial=1)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import redirect
from django.views.decorators.http import require_POST
from django.views.generic import TemplateView

from shop.utils import *
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Products, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Products, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


class CartDetailView(DataMixin, TemplateView):
    template_name = 'cart/detail.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title='Корзина')
        return dict(list(context.items()) + list(c_def.items()))

cart/templates/cart/detail.html
{% extends "shop/base.html" %}
{% block content %}
{% if cart|length == 0 %}
<script>window.location.href = "/";</script>
{% endif %}
<br>
{{ context }}
<section class="main-content">
  <div class="container">
  {% for item in cart %}
    {% with product=item.product %}
    <div class="row align-items-center">
      <div class="col-2">
            <a href="{% url 'shop:product' product.slug %}"><img src="{{ product.image.url }}" width="150" height="80"></a>
      </div>
      <div class="col">
          {{ product.product_name }}
      </div>
      <div class="col text-center">
        <form action="{% url 'cart:cart_add' product.id %}" id="form_buying_product" method="post">
          <span class="input-group-btn">
            <button type="submit" class="btn btn-default" name="quantity" value="{{ item.update_quantity_form.quantity.value|add:'-1' }}">-</button>
          </span>
          {{ item.quantity }}
          {{ item.update_quantity_form.update }}
          <span class="input-group-btn">
          <button type="submit" class="btn btn-default" name="quantity" value="{{ item.update_quantity_form.quantity.value|add:'1' }}">+</button>
          </span>
          {% csrf_token %}

        </form>

      </div>
      <div class="col text-center">
        Цена: {{ product.price }} Руб.
      </div>
      <div class="col text-center">
        Сумма: {{ item.total_price }} Руб.
      </div>
      <div class="col d-grid gap-2 d-md-flex justify-content-md-end">
        <a class="btn btn-danger" href="{% url 'cart:cart_remove' product.id %}">X</a>
      </div>
    </div>
      <hr>
        {% endwith %}
      {% endfor %}
    <div class="row align-items-center">
      <div class="col-9">
        <h3>Общая стоимость заказа: {{ cart.get_total_price }} Руб.</h3>
      </div>
      <div class="col d-grid gap-2 d-md-flex justify-content-md-end">
      <a href="{% url 'orders:order_create' %}" class="btn btn-success btn-lg">К оформлению заказа</a>
        <a href="{% url 'shop:shop' %}" class="btn btn-primary btn-lg">К покупкам</a>
      </div>
    </div>
  </div>
</section>
{% endblock %}