cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.CartDetailView.as_view(), name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

food_delivery_service/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from shop.views import *
from django.views.decorators.csrf import csrf_exempt

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('orders.urls', namespace='orders')),
    path('', include('shop.urls')),
    path('shop', include('shop.urls', namespace='shop')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('webhook/', csrf_exempt(my_webhook_handler))
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        # ...
        path('__debug__/', include('debug_toolbar.urls')),
    ] + urlpatterns

    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = pageNotFound

shop/urls.py
from django.urls import path
from .views import *
from django.views.decorators.csrf import csrf_exempt

app_name = 'shop'

urlpatterns = [
    path('', ProductsHome.as_view(), name='shop'),
    path('<slug>', ProductsHome.as_view(), name='shop'),
    path('city/<slug:city_slug>', city_slug, name='city_slug'),
    path('contacts/', contacts, name='contacts'),
    path('jobs/', jobs, name='jobs'),
    path('category/<slug:cat_slug>/', ProductsCategory.as_view(), name='category'),
    path('product/<slug:post_slug>/', ShowProduct.as_view(), name='product'),
    path('webhook/', csrf_exempt(my_webhook_handler))
]

shop/models.py
from django.urls import reverse
from django.db import models
from recipes.models import Recipes
from organizations.models import Cities


class Products(models.Model):
    image = models.ImageField(upload_to='static/image/%Y/%m/%d/', verbose_name='Изображение')
    product_name = models.CharField(max_length=50, verbose_name='Наименование')
    slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name="URL")
    short_description = models.CharField(max_length=35, verbose_name='Краткое описание')
    full_description = models.TextField(verbose_name='Полное описание')
    recipe = models.ForeignKey(Recipes, on_delete=models.CASCADE, verbose_name='Рецепт')
    shelf_life = models.ForeignKey('ShelfLife', on_delete=models.CASCADE, verbose_name='Срок годности')
    price = models.IntegerField(verbose_name='Цена')
    cities = models.ManyToManyField(Cities, verbose_name='Города обслуживания')
    menu_categories = models.ManyToManyField('MenuCategories', verbose_name='Категория блюда')
    queue = models.IntegerField(editable=False, default=0, verbose_name='Рейтинг')
    time_create = models.DateTimeField(auto_now_add=True, verbose_name='Создано')
    time_update = models.DateTimeField(auto_now=True, verbose_name='Обнавлено')
    publication = models.BooleanField(default=True, verbose_name='Опубликовано')

    class Meta:
        db_table = 'products'
        verbose_name = 'блюда'
        verbose_name_plural = 'Блюда'
        ordering = ['id']

    def __str__(self):
        return self.product_name

    def get_absolute_url(self):
        return reverse('product', kwargs={'post_slug': self.slug})


class MenuCategories(models.Model):
    categorie = models.CharField(max_length=20, db_index=True, verbose_name='Категория')
    slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name="URL")
    queue = models.IntegerField(verbose_name='Очередность')

    class Meta:
        db_table = 'menu_categories'
        verbose_name = 'категорию '
        verbose_name_plural = 'Категории блюд'

    def __str__(self):
        return self.categorie

    def get_absolute_url(self):
        return reverse('category', kwargs={'cat_slug': self.slug})


class ShelfLife(models.Model):
    shelf_life = models.CharField(max_length=50, verbose_name='Срок годности')

    class Meta:
        db_table = 'shelf_life'
        verbose_name = 'срок годности'
        verbose_name_plural = 'сроки годности'

    def __str__(self):
        return self.shelf_life

shop/views.py
import json
from django.http import HttpResponse
from yookassa.domain.notification import WebhookNotification
from django.http import HttpResponseNotFound, JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import ListView, DetailView
from .utils import *
from recipes.models import *
from django.db.models import Sum
from django.db.models.functions import Round
from django.shortcuts import render, redirect
from orders.tasks import payment_search
from yookassa import Payment


class BaseClassProduct(DataMixin, ListView):
    model = Products
    template_name = 'shop/index.html'
    context_object_name = 'products'


class ProductsHome(BaseClassProduct):
    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title='Магазин')
        return dict(list(context.items()) + list(c_def.items()))

    def get_queryset(self):
        user_context = self.get_user_context()
        city_id = user_context['city']['city_id']
        return Products.objects.filter(cities=city_id, publication=True).exclude(id__in=self.get_cart())


class ProductsCategory(BaseClassProduct):
    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title=f'Категория - {str(MenuCategories.objects.get(slug=self.kwargs["cat_slug"]))}',
                                      cat_selected=self.kwargs['cat_slug'])
        return dict(list(context.items()) + list(c_def.items()))

    def get_queryset(self):
        user_context = self.get_user_context()
        city_id = user_context['city']['city_id']
        return Products.objects.filter(menu_categories__slug=self.kwargs['cat_slug'],
                                       cities=city_id, publication=True).exclude(id__in=self.get_cart())


class ShowProduct(DataMixin, DetailView):
    model = Products
    template_name = 'shop/product.html'
    slug_url_kwarg = 'post_slug'
    context_object_name = 'product'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        obj = self.object
        context['ingredients'] = AddIngredientToRecipe.objects.filter(recipe=obj.id).prefetch_related('ingredient')
        context['kjby'] = AddIngredientToRecipe.objects.filter(recipe=obj.id).aggregate(
            withs=Sum(obj.recipe.serving_weight) / Count(obj.recipe.serving_weight),
            kcal=Round(Sum('kcal') * obj.recipe.serving_weight / Sum('weight'), 2),
            fats=Round(Sum('fats') * obj.recipe.serving_weight / Sum('weight'), 2),
            squirrels=Round(Sum('squirrels') * obj.recipe.serving_weight / Sum('weight'), 2),
            carbs=Round(Sum('carbs') * obj.recipe.serving_weight / Sum('weight'), 2)
        )

        c_def = self.get_user_context(title=context['product'])
        return dict(list(context.items()) + list(c_def.items()))

    def get_queryset(self):
        user_context = self.get_user_context()
        city_id = user_context['city']['city_id']
        return Products.objects.filter(cities=city_id, publication=True)


def city_slug(request, city_slug):
    request.session.pop('cart', None)
    city = Cities.objects.get(slug=city_slug)
    values = {'city_id': city.id, 'city_name': city.city, 'city_slug': city.slug}
    request.session['city'] = values
    return redirect('shop:shop')


def jobs(request):
    return render(request, 'shop/jobs.html', {'menu': menu, 'title': 'Вакансии'})


def contacts(request):
    return render(request, 'shop/contacts.html', {'menu': menu, 'title': 'Контакты'})


def pageNotFound(request, exception):
    return HttpResponseNotFound('<h1>Страница не найдена</h1>')


@csrf_exempt
def my_webhook_handler(request):
    try:
        event_json = json.loads(request.body)
    except json.decoder.JSONDecodeError:
        return HttpResponse(status=400)
    notification_object = WebhookNotification(event_json)
    payment = notification_object.object
    payment_log = Payment.find_one(payment.id)
    if payment_log.status == 'succeeded':
        payment_search.delay(payment.id)
        return HttpResponse(status=200)
    return HttpResponse(status=400)

shop/templates/shop/base.html
{% load static %}
{% load cache %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>{{title}}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/suggestions-jquery@21.12.0/dist/css/suggestions.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="{% static 'shop/css/main.css' %}"}>
    <script src="https://code.jquery.com/jquery-3.7.0.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <script src="https://yookassa.ru/checkout-widget/v1/checkout-widget.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/suggestions-jquery@21.12.0/dist/js/jquery.suggestions.min.js"></script>
</head>
<body>
{% block mainmenu %}
<div class="container">
    <header>
        <br>
        <div class="row align-items-center">
            <div class="col">
                <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none">
                    <span class="fs-3">Simple header</span>
                </a>
            </div>
            <div class="col">
                <button type="button" class="btn btn-light" data-bs-toggle="modal" data-bs-target="#exampleModal">
                    {{ city.city_name }}
                </button>
            </div>
            <div class="col">
                +7 (000) 000-00-00
            </div>
            <div class="col">
              <div class="btn-group" role="group">
                  {% for m in menu %}
                    <a class="btn btn-light text-uppercase" href="{% url 'shop:shop' m.url_name %}" role="button">{{ m.title }}</a>
                  {% endfor %}
              </div>
            </div>
        </div>
        <hr>
    </header>
</div>
{% endblock mainmenu %}
{% block categories %}
<nav class="navbar sticky-top navbar-light bg-light">
  <div class="container">
    <div class="btn-group col align-self-center" role="group">
      {% for c in categories %}
        {% if c.products__count > 0 %}
          {% if c.slug != cat_selected %}
            <a class="btn btn-outline-secondary text-uppercase" href="{% url 'shop:category' c.slug %}" role="button">{{ c.categorie }}</a>
          {% else %}
            <a class="btn btn-outline-secondary text-uppercase active" href="{% url 'shop:category' c.slug %}" role="button">{{ c.categorie }}</a>
          {% endif %}
        {% endif %}
      {% endfor %}
        {% with total_items=cart|length %}
        {% if cart|length > 0 %}
           <a href="{% url 'cart:cart_detail' %}" class="btn btn-outline-success" type="button"> Корзина: {{ cart.get_total_price }} Руб.</a>
        {% else %}
        <button class="btn btn-secondary" type="button">Ваша корзина пуста</button>
        {% endif %}
    {% endwith %}
    </div>
  </div>
</nav>
{% endblock categories %}
{% block content %}
{% endblock %}
<script src="{% static 'shop/js/scripts.js' %}"></script>
{% block paginator %}
{% if page_obj.has_other_pages %}
<br>
<nav aria-label="...">
    <div class="container">
      <ul class="pagination justify-content-center pagination-lg">
          {% if page_obj.has_previous %}
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">&lt</a></li>
          {% endif %}
          {% for p in paginator.page_range %}
              {% if page_obj.number == p %}
                <li class="page-item active" aria-current="page">
                    <span class="page-link">{{ p }}</span>
                </li>
              {% elif p >= page_obj.number|add:-2 and p <= page_obj.number|add:2 %}
                <li class="page-item"><a class="page-link" href="?page={{ p }}">{{ p }}</a></li>
              {% endif %}
          {% endfor %}
          {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}">&gt</a>
            </li>
          {% endif %}
      </ul>
    </div>
</nav>
{% endif %}
{% endblock paginator%}
{% block modal_city %}
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Выберите город</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Закрыть"></button>
      </div>
      <div class="modal-body">
          <div id="payment-form"></div>
          <div class="row">
              {% for city in cities %}
              <div class="col-5">
                  <form action="{% url 'shop:city_slug' city.slug %}" method="post">
                       <button type="submit" class="btn btn-light">{{ city }}</button>
                      {% csrf_token %}
                  </form>
              </div>
              {% endfor %}
          </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}
</body>
</html>

shop/templates/shop/contacts.html
{% extends 'shop/base.html' %}

{% block content %}

{% endblock %}

shop/templates/shop/delivery.html
{% extends 'shop/base.html' %}
{% block content %}

{% endblock %}

shop/templates/shop/index.html
{% extends 'shop/base.html' %}
{% block content %}
<br>
<section class="main-content">
  <div class="container">
    <div class="row row-cols-1 row-cols-md-3 g-4">
      {% for product in products %}
        <div class="col">
          <div class="card h-100 border-0 shadow p-0 mb-3 bg-body rounded">
            <a href="{% url 'shop:product' product.slug %}">
              <img src="{{ product.image.url }}" class="card-img-top" alt="{{ p.product_name }}">
            </a>
            <div class="card-body">
              <h5 class="card-title">{{ product.product_name }}</h5>
              <p class="card-text">{{ product.short_description }}</p>
              <div class="d-flex justify-content-between align-items-center">
                <form action="{% url 'cart:cart_add' product.id %}" method="post">
                  <button type="submit" class="btn btn-lg btn-outline-success">в корзину</button>
                  <input type="hidden" name="quantity" id="myHidden" value="1">
                    {% csrf_token %}
                </form>
                <h4><small class="text-body-secondary">{{ product.price }} руб.</small></h4>
              </div>
            </div>
          </div>
      </div>
      {% endfor %}
    </div>
  </div>
</section>
<br>
{% endblock %}

shop/templates/shop/jobs.html
{% extends 'shop/base.html' %}

{% block content %}

{% endblock %}

shop/templates/shop/list_categories.html
<nav class="navbar sticky-top navbar-light bg-light">
  <div class="container">
      {% for c in categories %}
          {% if c.products__count > 0 %}
            {% if c.slug != cat_selected %}
              <div class="btn-group btn-group-lg" data-bs-toggle="buttons">
                  <a href="{{ c.get_absolute_url }}" class="text-uppercase"><label class="btn btn-light">{{ c.categorie }}</label></a>
              </div>
            {% else %}
              <div class="btn-group btn-group-lg" data-bs-toggle="buttons">
                  <a href="{{ c.get_absolute_url }}" class="text-uppercase"><label class="btn btn-light active" role="button" data-bs-toggle="button" aria-pressed="true">{{ c.categorie }}</label></a>
              </div>
            {% endif %}
          {% endif %}
      {% endfor %}
  </div>
</nav>

shop/templates/shop/product.html
{% extends 'shop/base.html' %}
{% block content %}
<br>
<section class="main-content">
  <div class="container">
      <div class="card p-0 border-0 shadow-lg p-3 mb-5 bg-body rounded">
        <div class="row align-items-center">
          <div class="col-6">
          <img src="{{ product.image.url }}" class="card-img-top shadow-lg p-2 mb-3 bg-body rounded" alt="{{ product.product_name }}">
          </div>
          <div class="col">
             <h1>{{ product.product_name }}</h1>
            <h3>{{ product.short_description }}</h3>
             <p class="card-text">{{ product.full_description }}</p>
            <p>ВЕС ПОРЦИИ: {{ kjby.withs }} грамм, ЭНЕРГЕТИЧЕСКАЯ ЦЕННОСТЬ: {{ kjby.kcal }} ккал</p>
            {% if not product.id|stringformat:'s' in request.session.cart %}
                <form action="{% url 'cart:cart_add' product.id %}" id="form-product" method="post">
                  <div class="row align-items-center">
                    <div class="col text-center">
                        <h2 class="text-success">{{ product.price }} руб.</h2>
                    </div>
                    <div class="col-5 text-center">
                      <span style="font-size: 27px" class="text-secondary">Кол-во: </span><br>
                    <span class="input-group-btn">
                        <button class="btn btn-outline-secondary" id="minus" type="button">-</button>
                    </span>
                    &nbsp;&nbsp;<span style="font-size: 25px" class="text-primary" id="output">1</span>&nbsp;&nbsp;
                    <input type="hidden" name="quantity" id="myHidden" value="1">
                    <span class="input-group-btn">
                      <button class="btn btn-outline-secondary" id="plus" type="button">+</button>
                    </span>
                  </div>
                  <div class="col">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-lg btn-outline-success">в корзину</button>
                  </div>
                  </div>
                  <br>
                </form>
                 </div>
            </div>
                {% else %}
                <div class="col text-center">

                   <li class="list-group-item list-group-item-warning">
                     <br>
                     <h5>Товар уже добавлен в корзину!</h5>
                     <br>
                   </li>
                </div>
                {% endif %}

        </div>
        <div class="container text-center">
          <hr>
          <div class="row">
            <div class="col">
              ПИЩЕВАЯ ЦЕННОСТЬ<br>
              <hr>
              Жиры: {{ kjby.fats }},
              Белки: {{ kjby.squirrels }},
              Углеводы: {{ kjby.carbs }}
            </div>
            <div class="col-6">
              СОСТАВ:<br>
              <hr>
              {% for i in ingredients %}{{ i.ingredient }}: {{ i.weight }}г, {% endfor %}
            </div>
            <div class="col">
              СРОК ГОДНОСТИ:<br>
              <hr>
              {{ product.shelf_life }}
            </div>
          </div>
        </div>
        <br>
      </div>
</section>
<br>
{% endblock %}